[build]
  publish = "public"
  functions = "functions"  # Diretório onde suas funções serverless estão
  
[[redirects]]
  from = "/login/*"
  to = "/login/login.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[environment]
  API_KEY = "ENV_API_KEY"
  BIN_ID = "ENV_BIN_ID"
